### ISSUE TITLE
Cannot load ckpts in Dataset

### ISSUE THREAD

**Issue by thj2333** [rahul-goel/isrf_code#3]
Hi Rahul,

Thanks for your great work!

I have some troubles with load "data.pkl" in your released Dataset, could you give some suggestion for me? Here are my code:
`import torch
file=open("./trex/besht/data.pkl","rb")
data = torch.load(file)`

Here is the error:
> Traceback (most recent call last):
>   File "/home/isrf_code/ckpts/load_ckpt.py", line 3, in <module>
>     data = torch.load(file)
>   File "/home/anaconda3/envs/isrf/lib/python3.9/site-packages/torch/serialization.py", line 795, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/home/anaconda3/envs/isrf/lib/python3.9/site-packages/torch/serialization.py", line 1002, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: A load persistent id instruction was encountered,
> but no persistent_load function was specified.

And below are my pytorch version:
```
Python 3.9.16 (main, Mar  8 2023, 14:00:05) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.13.1+cu116'
```
Thanks!

**Comment by rahul-goel** [comment]
Hi!
I see what is causing the confusion. Following [DVGO's](https://github.com/sunset1995/DirectVoxGO) convention, I saved checkpoints using the `.tar` extension.

People may confuse it as an archived file and may try to extract it. Thank you for pointing this out. I'll explicitly mention this point in the dataset's readme file.

Please run `model = torch.load("./trex.tar")` to load it. Let me know if this doesn't work for you. As an alternative, you can also pass the path to this checkpoint using the `--ft_path` flag from `run.py` or `gui.py`.

**Comment by thj2333** [comment]
Thanks for the quick response! It works well now!
