### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by tourbliu** [rahul-goel/isrf_code#6]
Hello. Thank you so much for your wonderful work.but I have some questions about the experiment.When I installed the dependencies according to the readme, the following problem occurred:

Loading extension module adam_upd_cuda...
Traceback (most recent call last):
  File "/media/ISRF/isrf_code-main/run.py", line 14, in <module>
    from lib import utils, dvgo, dcvgo, dmpigo
  File "/media/ISRF/isrf_code-main/lib/utils.py", line 11, in <module>
    from .masked_adam import MaskedAdam
  File "/media/ISRF/isrf_code-main/lib/masked_adam.py", line 7, in <module>
    adam_upd_cuda = load(
  File "/home/sx639-2/.conda/envs/isrf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/sx639-2/.conda/envs/isrf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1534, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/sx639-2/.conda/envs/isrf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1936, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/sx639-2/.cache/torch_extensions/py39_cu116/adam_upd_cuda/adam_upd_cuda.so: cannot open shared object file: No such file or directory

My environment is configured as follows:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

torch version : 1.13.1+cu116
torchvision vision : 0.14.1+cu116
torch_scatter : 2.0.9+cu116

**Comment by rahul-goel** [comment]
Hi.

I remember facing a similar issue before. I don't remember the exact solution but it was related to the version of cuda. According to nvcc, your version is 11.7. Can you try bumping it up to 11.8 since that is what we tested it with.

Let me know whether this works or not.

Regards,
Rahul Goel

**Comment by tourbliu** [comment]
> Hi.
> 
> I remember facing a similar issue before. I don't remember the exact solution but it was related to the version of cuda. According to nvcc, your version is 11.7. Can you try bumping it up to 11.8 since that is what we tested it with.
> 
> Let me know whether this works or not.
> 
> Regards, Rahul Goel

Thank you for your reply. I changed cuda to 11.8 and still had the same problem. In addition, I also tried cuda version 11.3 and had the same problem.

**Comment by rahul-goel** [comment]
Thanks for letting me know. I would like to point you to a similar issue rasied on DVGOs repository since we have taken code from them: https://github.com/sunset1995/DirectVoxGO/issues/24

Seems like an issue with the version of GCC compiler when the CUDA extension is attempted to be compiled.

Please let me know whether this works or not.

Regards,
Rahul Goel

**Comment by tourbliu** [comment]
> Thanks for letting me know. I would like to point you to a similar issue rasied on DVGOs repository since we have taken code from them: [sunset1995/DirectVoxGO#24](https://github.com/sunset1995/DirectVoxGO/issues/24)
> 
> Seems like an issue with the version of GCC compiler when the CUDA extension is attempted to be compiled.
> 
> Please let me know whether this works or not.
> 
> Regards, Rahul Goel
Thank you for your reply. I have also seen this problem, and I have tried this solution, but the same error still occurs.

**Comment by tourbliu** [comment]
> Thanks for letting me know. I would like to point you to a similar issue rasied on DVGOs repository since we have taken code from them: [sunset1995/DirectVoxGO#24](https://github.com/sunset1995/DirectVoxGO/issues/24)
> 
> Seems like an issue with the version of GCC compiler when the CUDA extension is attempted to be compiled.
> 
> Please let me know whether this works or not.
> 
> Regards, Rahul Goel

Thank you for your reply. I have also seen this problem, and I have tried this solution, but the same error still occurs.

**Comment by tourbliu** [comment]
If possible, could you please send us the environment of your experiment? Thank you!

**Comment by rahul-goel** [comment]
![image](https://github.com/rahul-goel/isrf_code/assets/54021162/604d9776-0c22-4200-8a6c-d1402f52fa9d)

Here you go. Hope this helps.
Regards,
Rahul Goel

**Comment by tourbliu** [comment]
> ![image](https://user-images.githubusercontent.com/54021162/265250179-604d9776-0c22-4200-8a6c-d1402f52fa9d.png)
> 
> Here you go. Hope this helps. Regards, Rahul Goel

Thanks to your help, I was able to run on the command line after using this configuration. Thank you so much!!
