### ISSUE TITLE
Glfw Error 65544: X11: The DISPLAY environment variable is missing

### ISSUE THREAD

**Issue by wangluna** [rahul-goel/isrf_code#7]
I ran into this problem when running gui.py. 
<img width="797" alt="微信图片_20231130194256" src="https://github.com/rahul-goel/isrf_code/assets/60725026/90f987f5-a093-458f-8641-be7bdb7eb1cf">

My operating system is Windows 10, and I use SSH to connect to the remote server to run commands. I would like to ask how to display the graphical interface in this situation. Thank you very much for taking the time to answer my questions.

**Comment by rahul-goel** [comment]
Hello.

This issue seems to be popping up because you're using a remote machine. You've SSHed into a machine and are trying to launch a graphical interface which doesn't work.

A solution to this is to use X forwarding. However, I'm not sure how well X forwarding works on Windows.

Regards,
Rahul Goel

**Comment by wangluna** [comment]
Yes, you are right. I have tried X forwarding but it didn't work. Thank you very much for your patient reply.

**Comment by wangluna** [comment]
Thank you very much for your patient reply.&nbsp;I have tried X forwarding but it didn't work. This is very unfortunate.




WLN
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rahul-goel/isrf_code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月30日(星期四) 晚上10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rahul-goel/isrf_code] Glfw Error 65544: X11: The DISPLAY environment variable is missing (Issue #7)





 
Closed #7 as completed.
